Login register functionality
Duckus6/movie-match pull request #73
Opened 2022-02-02 23:18 UTC by Jack0001

authentication functionality and some error reporting for successful and failed login attempts
registering user functionality added

2022-02-03 14:48 UTC, Duckus6 requested changes

2022-02-03 14:48 UTC, Duckus6 commented on pages/components/LoginForm.js
> +        fetch('http://localhost:3001/login', {
Can't manually code the url for routing. See https://nextjs.org/docs/routing/introduction for more information

2022-02-03 14:48 UTC, Duckus6 commented on pages/components/LoginForm.js
> +    handleChange = event => {
Is there any particular reason why you aren't using Use state/Use effect React hooks?

2022-02-03 14:48 UTC, Duckus6 commented on pages/components/LoginForm.js
> +    handleSubmit = event => {
Use effect should be used instead

2022-02-03 14:48 UTC, Duckus6 commented on pages/components/LoginForm.js
> +    render() {
You do not need to use render from react-dom at all with page creation as far as im aware. This is likely a legacy thing from a tutorial you looked at or somethign that is done automatically in nextjs.

2022-02-03 14:48 UTC, Duckus6 commented on pages/components/RegisterForm.js
> +    handleChange = event => {
See above about useState/useEffect

2022-02-03 14:48 UTC, Duckus6 commented on pages/components/RegisterForm.js
> +        fetch('http://localhost:3001/register', {
See above about manual url's

2022-02-03 14:48 UTC, Duckus6 commented on pages/components/RegisterForm.js
> +    render() {
See above about render()

2022-02-03 14:48 UTC, Duckus6 commented on server/server.js
> +const express = require('express');
We do not need to use express.js at all in our code. Nextjs has its own client side routing which we have examples for. Is there any reason why you chose not to use this?

2022-02-03 14:48 UTC, Duckus6 commented on server/server.js
> +            userName: 'qp4mX84QfiLGeK',
You should NEVER hardcode username and password, especially if you're pushing this to a branch. 

Is it meant to be userName or should it be username

2022-02-03 14:48 UTC, Duckus6 commented on server/server.js
> +            .then(() => {
It is better practice to use async/awaits and have it as an asynchronous function then to do it like this

2022-02-03 14:48 UTC, Duckus6 commented on server/server.js
> +            .then(() => {
See above on async/await

2022-02-03 14:48 UTC, Duckus6 commented on server/server.js
> +const { Request, TYPES } = require('tedious');
Is there any reason you're using tedious? Is there any reason you aren't using mssql? Likewise is there any reason you did not partake in the discussion we had in discord on mssql?

2022-02-03 14:48 UTC, Duckus6 commented on server/server.js
> +        request.addParameter('password', TYPES.NVarChar, password);
Not certain but are passwords hashed in the database or should they be hashed on the front ned?

2022-02-03 14:48 UTC, Duckus6 commented on data/users.json
> +[]
This file currently does nothing

2022-02-04 16:41 UTC, Jack0001 commented on pages/components/LoginForm.js
> +    render() {
changed

2022-02-04 17:57 UTC, Duckus6 commented on pages/components/LoginForm.js
> +    handleSubmit = event => {
You are indeed correct I forgot this is in the context of a form and not a "makeshift" form where you would have a usestate's value changed to trigger the useEffect.

2022-02-04 18:23 UTC, Jack0001 commented on server/server.js
> +const express = require('express');
express is being used here for backend purposes, this will need to be moved to the backend repo and is mainly just here for review purposes

2022-02-04 18:23 UTC, Jack0001 commented on server/server.js
> +            userName: 'qp4mX84QfiLGeK',
will change username and password to be environment variables

2022-02-04 18:23 UTC, Jack0001 commented on server/server.js
> +const { Request, TYPES } = require('tedious');
tedious is just a wrapper for mssql to make it easier to use,  i cant see any discord messages about using mssql so if theres a specific reason then i can change over

2022-02-08 12:15 UTC, Duckus6 approved these changes

2022-02-08 12:15 UTC, merged